similarity_search/src/method/hnsw.cc

This fixes a mem access violation problem in the default destructor in the case where an index is empty and no ptrs are allocated

Update hnsw.cc with default values and null ptr

---

similarity_search/include/sort_arr_bi.h

while moving 0 bytes is ok
when : curr + 1 == num_elems_
an access violation: &v_[curr+1]
I encountered this error when keys are equal and que is full

Orgoro memove0bytes mem acces violation

---

.gitignore
python_vect_bindings/setup.py
similarity_search/include/simd.h
similarity_search/include/sort_arr_bi.h
similarity_search/src/method/hnsw.cc
similarity_search/src/method/hnsw_distfunc_opt.cc

These are the changes I had to make to get nmslib to build on os x with anaconda. They are:
1. explicitly including `x86intrin.h` or equivalent for your CPU architecture
2. adding a setup.py script for python_vect_bindings so that it uses the correct include paths

Get nmslib and python_vect_bindings to build on mac

---

similarity_search/CMakeLists.txt
similarity_search/include/experimentconf.h
similarity_search/include/space/space_sparse_vector.h
similarity_search/src/main.cc
similarity_search/src/space.cc
similarity_search/src/tune_vptree.cc
similarity_search/test/test_clust.cc
similarity_search/test/test_integr_util.h

1. Allow to build without tests via WITHOUT_TESTS cmake
2. Fix bugs in types. Before this commit it was impossible to compile project without fatal errors if you change IdType typedef in IdType.h file

add WITHOUT_TESTS, fix IdType bugs

---

similarity_search/test/test_space_scalar.cc

Note: This only verifies the correctness of the distance function used by SpaceNegativeScalarProduct (in the same way as is done for SpaceLp in test_lpnorm.cc). It does not add any end to end indexing/performance testing.

Adding a unit test to validate correctness for SpaceNegativeScalarProduct: #191

---

python_bindings/nmslib.cc
python_bindings/setup.py
python_bindings/tests/bindings_test.py

When switching the bindings away from using openmp, I introduced a segfault that would happen when the num_threads parameter wasn't specified in knnQueryBatch. 
num_threads was being defaulted to 0 - which for openmp specifies to use the number of cores, but here means no worker threads get created in knnQueryBatch.
Fixed, and added a unittest that would have caught this.

fix potential segfault

---

python_bindings/nmslib.cc
python_bindings/setup.py
python_bindings/tests/bindings_test.py
similarity_search/include/memory.h
similarity_search/include/method/hnsw.h
similarity_search/include/method/small_world_rand.h
similarity_search/include/space/space_ab_diverg.h
similarity_search/include/space/space_sparse_vector.h
similarity_search/src/distcomp_sparse_scalar_fast.cc
similarity_search/src/method/hnsw.cc

1) Fixed some errors found by valgrind
indexThreadQty in hnsw.cc wasn't initialized on osx, causing some chaos. Default to 1 without
openmp
```
==78687== Conditional jump or move depends on uninitialised value(s)
==78687==    at 0x101B2D419: similarity::VisitedListPool::VisitedListPool(int, int) (hnsw.h:588)
```
Also fixed this:
```
==44990== Mismatched free() / delete / delete []
==44990==    at 0x4C2C2BC: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==44990==    by 0x4763B8: ~VisitedList (hnsw.h:571)
```
2) Fixed various compiler warnings (mainly on osx)
```
./nmslib/similarity_search/include/method/hnsw.h:582:13: warning: private field 'maxpools' is not used [-Wunused-private-field]
./nmslib/similarity_search/include/memory.h:31:8: warning: private …
```

Assorted minor fixes.

---

.travis.yml

With this change, the travis build fails on OSX when bunit fails:
https://travis-ci.org/benfred/nmslib/builds/238841730

fail travis build on error

---

python_bindings/nmslib.cc
similarity_search/include/thread_pool.h
similarity_search/src/method/hnsw.cc
similarity_search/test/test_thread_pool.cc

Add a ParallelFor function with the goal of removing openmp
as a dependency.
This enables multi-threaded indexing for HNSW on OSX - as well
as fixes a problem in the python bindings with knnQueryBatch
where if a thread threw an exception the exception wouldn't
be propagated to the main thread (fix as suggested in issue #178).
(Re-opened PR on the develop branch).

add a ParallelFor function

---

similarity_search/include/method/hnsw.h
similarity_search/src/method/hnsw.cc

Here are several fixes in the HNSW index. Each fix is in its own commit.
The most significant one is the leak of link lists. It can leak a lot if indexes are loaded and destroyed multiple times during a program lifetime.

Fix memory leaks in HNSW

---

python_bindings/docs/api.rst
python_bindings/nmslib.cc

The formatting for knnQueryBatch is messed up because of a missing
newline: https://searchivarius.github.io/nmslib/api.html#nmslib.dist.FloatIndex.knnQueryBatch . Also listed out values for the DistType/DataType enums

Minor doc fixes

---

python_bindings/nmslib.cc
python_bindings/tests/bindings_test.py

Docstrings for addDataPoint/addDataPointBatch were cut and
paste incorrectly. Fix.
Also fix flake8 warning that is in the master branch, and is causing
this build to be marked as failing: https://github.com/searchivarius/nmslib/pull/234

Fix docstrings for addDataPoint/addDataPointBatch

---

python_bindings/docs/index.rst
python_bindings/docs/logging.rst
python_bindings/nmslib.cc
similarity_search/apps/tune_vptree.cc
similarity_search/include/logging.h
similarity_search/src/init.cc
similarity_search/src/logging.cc
similarity_search/src/space/space_bit_hamming.cc
similarity_search/src/space/space_dummy.cc
similarity_search/src/space/space_sparse_vector.cc
similarity_search/test/test_distfunc.cc

This change lets Python LogHandlers handle the log messages
produced by nmslib.
This lets python control the behaviour
of the log messages at run time, meaning that the loglevel
can be adjusted and that the output of the messages can
be handled any python loghandler.
This basically involves transforming the existing logger class into
an abstract base, and then creating a python version that adapts
the nmslib log system to the python version.

Allow Python Handling of log messages

---

.travis.yml

We were seeing an error on OSX build in travis, complaining about shell_session_update not being
found. This seems to be the same issue as here https://github.com/travis-ci/travis-ci/issues/6307
Fix by getting latest stable rvm.

Fix rvm issue on travis builds

---

.travis.yml

OSX build are taking too long to finish, mark these builds as optional (allow_failure), and then
set the 'fast_finish' flag so that we report the build as passing as soon as the linux builds
finish.
Also test out python3.6 on linux too, and build extras on linux as well.

travis CI changes

---

python_bindings/nmslib.cc

The default return_value_policy for py::cast calls is return_value_policy::automatic_reference
(as described here:
http://pybind11.readthedocs.io/en/stable/advanced/functions.html#return-value-policies).
This means that pybind was treating the index as a reference, and not taking ownership of it
and calling the desctructor when the python object was freed. Fix by explicitly telling
pybind to take ownership here.

Fix Memory Leak in Python Bindings.

---

python_bindings/nmslib.cc
python_bindings/tests/bindings_test.py

I introduced a bug in my previous commit, and passing ids to addDataPointBatch
wasn't being respected. Fix this, and add a unittest so that this will be caught
int the future.

Fix addDataPointBatch where ids != None

---

README.md
python_bindings/nmslib.cc

Pybind11 seems to have an issue in gil_scoped_acquire when being
called from child threads created from python. This resulted in a deadlock here:
https://github.com/searchivarius/nmslib/issues/291
A simple workaround is to use the PyGILState_Ensure from the python c-api directly
instead.

Fix deadlock in child threads launched from python

---

README.md
python_bindings/README.md

After the move to the nmslib organization, certain links were pointing to pages
that 404'ed (for instance https://travis-ci.org/searchivarius/nmslib and
https://searchivarius.github.io/nmslib/).
This updates the README to point to the correct location here. Note that I left
the appveyor link alone, since https://ci.appveyor.com/project/searchivarius/nmslib
seems to work and https://ci.appveyor.com/project/nmslib/nmslib doesn't yet.

update links in README

---

similarity_search/include/factory/init_methods.h
similarity_search/include/factory/method/bbtree.h
similarity_search/include/method/bbtree.h
similarity_search/src/CMakeLists.txt

* bbtree is licensed under GPL and will virally
cause this whole project to be under GPL if included
in the normal way

Remove bbtree if not compiling using WITH_EXTRAS

---

python_bindings/notebooks/README.md

The jaccard sparse link was pointing to the wrong notebook so I fixed it.

Fix wrong link in readme.MD

---

.travis.yml
python_bindings/nmslib.cc
python_bindings/tests/bindings_test.py

When NMSLIB is logging to the python logger, there can occasionally be exceptions
be thrown on system exit (https://github.com/nmslib/nmslib/issues/327).
Fix by trapping these exceptions since making a log call shouldn't throw an exception.

Don't throw exceptions when logging

---

python_bindings/setup.py
similarity_search/src/method/hnsw.cc
similarity_search/src/method/small_world_rand.cc
similarity_search/src/method/vptree.cc

'and' isn't a valid operator on C++ (though apparently works in linux), and
on some windows configurations we needed to include a different header file for
_mm_prefetch. Also if git wasn't configured with symlinks succesfully, fallback to a relative
path in setup.py.
Fixes https://github.com/nmslib/nmslib/issues/295 and https://github.com/nmslib/nmslib/issues/348

various windows build fixes

---

README.md
similarity_search/include/method/small_world_rand.h
similarity_search/src/method/small_world_rand.cc
test_batch_app/test_batch_mod.cc

This pull request fixes some bugs discussed in the issue https://github.com/nmslib/nmslib/issues/351
There are three bugfixes:
1) AddBatch checks if index is not empty. If so, it creates new neighbourless node, otherwise it adds elements in already created index.
2) DeleteBatch does not create any threads if indexThreadQty_==1.
3) Parameters initialization before index loading (method InitParamsManually).
4) Legacy test_batch_app library initialization (initLibrary) updated.

Bugfixes for small_world_rand batch addition/deletion and index loading

---

python_bindings/setup.py

This gives a workaround for cases where the library is built on one CPU, then attempts to run on an older one and fails due to illegal instructions. (frequently seen when deploying via docker). I've implemented the fix suggested in #325.
Resolves #325

Don't set -march=native if -march is set in CFLAGS

---

.appveyor.yml
.pypirc
.travis.yml
python_bindings/setup.py

This is a work in progress. Things that are yet to be sorted:
* the correct encrypted password should be added to `appveyor.yml` and to the Travis CI repository settings
* appveyor builds should be re-enabled for the repo
* x86 builds are currently throwing an error on appveyor:
<details>
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -I.\nmslib\similarity_search\include -Ic:\python36\Include -IC:\Users\appveyor\AppData\Roaming\Python\Python36\Include -Ic:\python36\Include -IC:\Users\appveyor\AppData\Roaming\Python\Python36\Include -Ic:\python36\lib\site-packages\numpy\core\include -Ic:\python36\include -Ic:\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft …
```

Automatically deploy to pypi on tag

---

python_bindings/requirements.txt

Looks like pybind fixed the issue https://github.com/nmslib/nmslib/issues/307 with older versions of pip, see this PR: https://github.com/pybind/pybind11/pull/1190
Upgrading to a newer version might help ease some installs.

require pybind11>=2.2.3

---

python_bindings/tensorflow/cpu_feature_guard.cc

`import nmslib` should not cause anything to be written to stdout.

Don't output unused instructions warning to STDOUT (use stderr)

---

python_bindings/notebooks/test_hnsw_recall.py

I happened to find and use this example script to bootstrap code for some recall testing I was doing. I noticed that index.setQueryTimeParams() was being applied after running the KNN queries, which was causing efS to be ignored and queries would use the library default instead (which I think is 20). The script is trying to set efS to 200 which makes the recall test results look worse than they should.
Before:
```
jschmitz28:~$ python test_hnsw_recall.py
Index-time parameters {'M': 30, 'indexThreadQty': 4, 'efConstruction': 200, 'post': 0}
Indexing time = 14.957313
kNN time total=0.028158 (sec), per query=0.000028 (sec), per query adjusted for thread number=0.000113 (sec)
Computing gold-standard data
Brute-force preparation time 0.007581
brute-force kNN time total=2.261873 (sec), per …
```

Fix call order for index.setQueryTimeParams() in test_hnsw_recall example

---

.travis.yml

The packages from the deadsnakes ppa are missing some files that are provided by core ubuntu packages. This adds those packages

python3.8: add ubuntu packages

---

.travis.yml

adds python3.8 distutils package
don't merge until the travis build succeeds - I'll keep working on it

Another try at getting python3.8 builds on travis

---

manual/build.md

`nmslib `is available as a port in [vcpkg](https://github.com/microsoft/vcpkg), a C++ library manager that simplifies installation for `nmslib `and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build `nmslib`, ready to be included in their projects.
We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64) to keep a wide coverage for users.
I'm a maintainer for vcpkg, and [here is what the port script looks like](https://github.com/microsoft/vcpkg/blob/master/ports/nmslib/portfile.cmake). We try to keep the library maintained as close as possible to the original library.

Add vcpkg installation instructions

---

similarity_search/include/method/hnsw_distfunc_opt_impl_inline.h
similarity_search/include/portable_intrinsics.h
similarity_search/include/portable_prefetch.h
similarity_search/include/portable_simd.h
similarity_search/include/sort_arr_bi.h
similarity_search/src/method/hnsw.cc
similarity_search/src/method/hnsw_distfunc_opt.cc
similarity_search/src/method/pivot_neighb_invindx.cc
similarity_search/src/method/small_world_rand.cc
similarity_search/src/method/vptree.cc
similarity_search/test/test_distfunc.cc
similarity_search/test/test_overlap.cc
similarity_search/test/test_some_stat.cc

This PR does some refactoring to add ARM compatibility to the library.
First, I added a `PREFETCH` Macro that maps to the correct prefetch function for the architecture used for compilation. For x86 and x64, it will map to `_mm_prefetch`. For aarch64, it will use gcc's `__builtin_prefetch`. For this, I was following a recommendation in [this post](https://stackoverflow.com/questions/16032202/how-to-use-pld-instruction-in-arm). I think it would be possible to embed assembly, but this seems like it may get a little complex. So, for a first version, I just used `__builtin_prefetch`, but can change if you think another implementation may be better. If the architecture is neither x86 nor aarch64, `PREFETCH` will default to a no-op. After making this change, I was able to compile and run …

Add ARM compatibility

---

.travis.yml
travis/deploy.sh

Travis-CI allows for the creation of aarch64 wheels.
Build: https://travis-ci.com/github/janaknat/nmslib/builds/205780637
There are 8-9 failures when testing hnsw. Any suggestions on how to fix these? A majority of the failures are due to expected=0.99 and calculated=~0.98.
Tagging @jmazanec15 since he added ARM compatibility.

Add support to build aarch64 wheels

---

python_bindings/nmslib.cc
python_bindings/requirements.txt
python_bindings/setup.py

logging.getLogger("nmslib") is not a module, so it can't be assigned to
a py::module.
Revert the changes to pin the pybind11 version.

Fix import on newer versions of pybind11 (fixes #471)

---

sample_standalone_app/sample_standalone_app1.cc
similarity_search/include/method/vptree.h
similarity_search/src/method/vptree.cc

Implements `VPTree::SaveIndex` and `VPTree::LoadIndex`.
Some implementation nodes: 
1. Nodes are saved in pre-order traversal order. This is implemented recursively, since the tree is never very deep (and the original construction of the tree happens recursively, too). I had originally used a non-recursive implementation but this was much more complicated because of the presence of sentinel nodes (see below).
2. Some nodes have 0 or 1 children. To distinguish between either case we write a sentinel value (-1.0) to file in case a child is NULL. Regular node data is serialized starting with the median distance (which is non-negative), so that upon loading we can check the first float value present, and distinguish between a NULL child and a regular child.
I am not a routined C++ programmer …

Save/load VPTree instances.

---

similarity_search/CMakeLists.txt

CMake uses “Apple Clang” for Apple clang :)

similarity_search: fix Apple clang detection
